; ── HAUPTEINSTELLUNGEN ──────────────────────────────────────────────
[platformio]
default_envs = Black_ota4M
src_dir       = src
include_dir   = include

; ── GEMEINSAME EINSTELLUNGEN ─────────────────────────────────────────
[env]
platform      = espressif8266
framework     = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
board_build.f_cpu = 160000000L

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
  bblanchon/ArduinoJson

build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
  -Os                              ; Größe optimieren statt Geschwindigkeit

; ====================================================================
; === 🟡 YELLOW (Gelbes Original-Board) ===
; ====================================================================

[env:Yellow]
board                  = esp12e
board_build.flash_mode = dout
upload_protocol        = esptool
upload_speed           = 115200

[env:Yellow_ota]
board                  = esp12e
board_build.flash_mode = dout
upload_protocol        = espota
upload_port            = 192.168.0.33
upload_flags           =
  --auth=sfasfasfasdfsadfasdfasdfasdfdsf


; ====================================================================
; === ⚫ BLACK 4M (Schwarzes Bastel-Board) ===
; ====================================================================

[env:Black4M]
board                    = esp12e
board_build.flash_mode   = dout
;board_build.ldscript     = eagle.flash.1m64.ld   ; 1MB Flash, 64KB SPIFFS -> mehr Platz für Sketch
upload_protocol          = esptool
upload_speed             = 115200

[env:Black_ota4M]
board                    = esp12e
board_build.flash_mode   = dout
;board_build.ldscript     = eagle.flash.1m64.ld
upload_protocol          = espota
upload_port              = 192.168.0.34
upload_flags             =
  --auth=sfasfasfasdfsadfasdfasdfasdfdsf


; ====================================================================
; === ⚫ BLACK (Schwarzes Bastel-Board) ===
; ====================================================================

[env:Black]
board                    = esp01_1m
board_build.flash_mode   = dout
board_build.ldscript     = eagle.flash.1m64.ld   ; 1MB Flash, 64KB SPIFFS -> mehr Platz für Sketch
upload_protocol          = esptool
upload_speed             = 115200

[env:Black_ota]
board                    = esp01_1m
board_build.flash_mode   = dout
board_build.ldscript     = eagle.flash.1m64.ld
upload_protocol          = espota
upload_port              = 192.168.0.34
upload_flags             =
  --auth=sfasfasfasdfsadfasdfasdfasdfdsf

; ====================================================================
; === 🧊 CUBE (wie Yellow, aber Bild horizontal gespiegelt) ===
; ====================================================================

[env:Cube_USB]
board                  = esp12e
board_build.flash_mode = dout
upload_protocol        = esptool
upload_speed           = 115200
build_flags =
  ${env.build_flags}
  -D CUBE_MIRROR

[env:Cube_OTA]
board                  = esp12e
board_build.flash_mode = dout
upload_protocol        = espota
upload_port            = 192.168.0.32
upload_flags           =
  --auth=sfasfasfasdfsadfasdfasdfasdfdsf
build_flags =
  ${env.build_flags}
  -D CUBE_MIRROR
